### ISSUE TITLE
covariates.txt missing from training data

### ISSUE THREAD

**Issue by rkayjay** [hakyimlab/PredictDB_Pipeline_GTEx_v7#1]
Can you add the covariates.txt file to the training data folder? It appears required for creating peer factors and running the final nested elastic net models.

**Comment by Fnyasimi** [comment]
@rkayjay You can generate the `covariates.txt` file by using the the gene expression data as below;
- Create a copy of the gene expression 
- Transpose the gene expression to have `samples as rows and genes as columns`
- Save the file in a `.csv` format
- Run Peer factors depending on the number of the samples
    ```
    According to GTEx protocol, If the number of samples is greater than or equal to 350, we use 60 PEER factors. 
    If the number of samples is between 250 and 350, we use 45. 
    Between 150 and 250, we use 30, and less than 150 we use 15. 
    ```
-  Add the sample id to colnames of the X.csv output of the peer factors and this will generate your covariates file for model training
- Adjust the expression using the covariates file by performing linear regression and use the transformed expression for model training

For more details check out this [section](https://github.com/hakyimlab/PredictDB-Tutorial/blob/master/analysis/PredictDB-Tutorial.Rmd#L88-L148)

**Comment by rkayjay** [comment]
Got it. Sorry for the naive question, I was thinking additional covariates were included.
